### ISSUE TITLE
Process [/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/bin/initdb ...] failed

### ISSUE THREAD

**Issue by chenjienn** [zonkyio/embedded-database-spring-test#103]
my spring boot test code :

```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class)
@AutoConfigureMockMvc
@ActiveProfiles("test")
@AutoConfigureEmbeddedDatabase
public class BaseControllerTest {
}
```
```
@Slf4j
public class DatasourceControllerTest extends BaseControllerTest {

    @Autowired
    MockMvc mockMvc;

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Test
    public void testSql() {
        String sql = "insert into test values (1)";

        jdbcTemplate.update(sql);

        String sql1 = "select id from test";

        long id = jdbcTemplate.queryForObject(sql1, Long.class);
        Assert.assertEquals(id, 1);
    }
}
```
my application-test.yaml is :
```
server:
  port: 8081

spring:
  datasource:
     schema: classpath:test-ddl.sql, classpath:test-dml.sql
  flyway:
    enabled: false
```
the error log is :
```
2020-06-19 11:50:16.433  INFO   --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.miotech.kun.datadiscover.DatasourceControllerTest], using SpringBootContextLoader
2020-06-19 11:50:16.439  INFO   --- [           main] o.s.t.c.support.AbstractContextLoader    : Could not detect default resource locations for test class [com.miotech.kun.datadiscover.DatasourceControllerTest]: no resource found for suffixes {-context.xml, Context.groovy}.
2020-06-19 11:50:16.622  INFO   --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener, io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener]
2020-06-19 11:50:16.635  INFO   --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@3514a4c0, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@212b5695, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@446293d, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@69997e9d, org.springframework.test.context.support.DirtiesContextTestExecutionListener@793be5ca, io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener@2df9b86, org.springframework.test.context.transaction.TransactionalTestExecutionListener@37654521, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@15aab8c6, org.springframework.test.context.event.EventPublishingTestExecutionListener@33990a0c, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@4de4b452, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@50b5ac82, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@101952da, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@6babf3bf, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@3059cbc]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.2.RELEASE)

2020-06-19 11:50:16.886  INFO 23723 --- [           main] c.m.k.d.DatasourceControllerTest         : Starting DatasourceControllerTest on jiechen-miotech-MacBook-Pro.local with PID 23723 (started by chenjie in /Users/chenjie/IdeaProjects/miotech/kun/kun-data-discover)
2020-06-19 11:50:16.886  INFO 23723 --- [           main] c.m.k.d.DatasourceControllerTest         : The following profiles are active: test
2020-06-19 11:50:17.560  INFO 23723 --- [           main] EmbeddedPostgresContextCustomizerFactory : Replacing 'dataSource' DataSource bean with embedded version
2020-06-19 11:50:17.759  INFO 23723 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-06-19 11:50:17.812  INFO 23723 --- [           main] eProvider$PriorityThreadPoolTaskExecutor : Initializing ExecutorService
2020-06-19 11:50:17.877  INFO 23723 --- [  prefetching-1] i.z.t.d.p.embedded.EmbeddedPostgres      : Detected a Darwin x86_64 system
2020-06-19 11:50:17.878  INFO 23723 --- [  prefetching-1] .z.t.d.p.e.DefaultPostgresBinaryResolver : Detected distribution: 'Unknown'
2020-06-19 11:50:17.880  INFO 23723 --- [  prefetching-1] .z.t.d.p.e.DefaultPostgresBinaryResolver : System specific postgres binaries found: postgres-darwin-x86_64.txz
2020-06-19 11:50:17.976  INFO 23723 --- [  prefetching-1] i.z.t.d.p.embedded.EmbeddedPostgres      : Extracting Postgres...
2020-06-19 11:50:20.089  INFO 23723 --- [  prefetching-1] i.z.t.d.p.embedded.EmbeddedPostgres      : Postgres binaries at /var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      : dyld: Library not loaded: @loader_path/../lib/libz.1.dylib
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      :   Referenced from: /private/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/lib/libxml2.2.dylib
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      :   Reason: image not found
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      : no data was returned by command ""/private/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/bin/postgres" -V"
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      : The program "postgres" is needed by initdb but was not found in the
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      : same directory as "/private/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/bin/initdb".
2020-06-19 11:50:20.186  INFO 23723 --- [itdb:pid(23725)] i.z.t.d.p.embedded.EmbeddedPostgres      : Check your installation.
2020-06-19 11:50:20.191  WARN 23723 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceController': Unsatisfied dependency expressed through field 'datasetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'datasetService': Unsatisfied dependency expressed through field 'datasetRepository'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'datasetRepository': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTemplate' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/JdbcTemplateConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': FactoryBean threw exception on object creation; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Process [/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/epg5664875353160425755, -E, UTF-8] failed
2020-06-19 11:50:20.202  INFO 23723 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-06-19 11:50:20.205 ERROR 23723 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceController': Unsatisfied dependency expressed through field 'datasetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'datasetService': Unsatisfied dependency expressed through field 'datasetRepository'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'datasetRepository': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTemplate' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/JdbcTemplateConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': FactoryBean threw exception on object creation; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Process [/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg/PG-b034c5076b1c309839a0c24aaf558849/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/epg5664875353160425755, -E, UTF-8] failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
```

I have tried to delete the directory `/var/folders/6v/p0nbr0v16lsg41g8c6cnwg3m0000gn/T/embedded-pg` but not work

**Comment by tomix26** [comment]
What versions of `embedded-database-spring-test` and `embedded-postgres-binaries` are you using?

**Comment by chenjienn** [comment]
> What versions of `embedded-database-spring-test` and `embedded-postgres-binaries` are you using?
```
testImplementation enforcedPlatform('io.zonky.test.postgres:embedded-postgres-binaries-bom:11.8.0')
testImplementation 'io.zonky.test:embedded-database-spring-test:1.5.4'
```

**Comment by tomix26** [comment]
You have to downgrade the `embedded-postgres-binaries` to version `11.6.0` because the last few versions are affected by the following issue: https://github.com/zonkyio/embedded-postgres-binaries/issues/21

Or, as an alternative, you can use [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) that runs the database in a docker container. In that case, you can use any available version.

**Comment by chenjienn** [comment]
thanks~
