### ISSUE TITLE
Spring Boot 2.3.1: Failed to replace DataSource with an embedded database for tests.

### ISSUE THREAD

**Issue by matthjes** [zonkyio/embedded-database-spring-test#108]
Hi,

I'm getting the following error when I try to start a test:
```
Caused by: java.lang.IllegalStateException: Failed to replace DataSource with an embedded database for tests. If you want an embedded database please put a supported one on the classpath or tune the replace attribute of @AutoConfigureTestDatabase.
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration$EmbeddedDataSourceFactory.getEmbeddedDatabase(TestDatabaseAutoConfiguration.java:179)
	at org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration$EmbeddedDataSourceFactoryBean.afterPropertiesSet(TestDatabaseAutoConfiguration.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 77 more
``` 

I'm using Spring Boot 2.3.1, Flyway 6.0.2 and version 1.5.4 of the embedded database. Here is my test class (in Kotlin):
```
@RunWith(SpringRunner::class)
@DataJpaTest
@AutoConfigureTestDatabase
class ConfigRepositoryTest {

    @Autowired
    private lateinit var configRepository: ConfigRepository

    @Test
    fun `should store config entity`() {
        val data = "Test data"
        val config = Config.Builder("testConfig", data).build()

        val saved = configRepository.save(config)
    }
}
```
Am I missing something here? According to the README, it should be enough to add the `@AutoConfigureTestDatabase` annotation.

**Comment by matthjes** [comment]
Sorry, used the wrong annotation...

**Comment by AlexandrSokolov** [comment]
@matthjes , what exactly was wrong, do you remember? I have the same issue with the same set of annotations. Cannot get it how to resolve the issue.

**Comment by matthjes** [comment]
I'm not sure, it's been a while. But I guess I replaced `@AutoConfigureTestDatabase` with `@AutoConfigureEmbeddedDatabase`...

**Comment by yash0923** [comment]
Please add this before your class.

@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)

it will run for sure.

**Comment by tomix26** [comment]
@yash0923 Since version 1.3.4, which was released 3 years ago, the annotation is no longer necessary.

https://github.com/zonkyio/embedded-database-spring-test/releases/tag/v1.3.4
> - Improved support for Spring Boot's test annotations
>   - Using @AutoConfigureTestDatabase(replace = NONE) is no longer required

**Comment by Hoxtygen** [comment]
> Please add this before your class.
> 
> @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
> 
> it will run for sure.

Worked for me. Almost gave up.

**Comment by tomix26** [comment]
@Hoxtygen What version of the library are you using?

**Comment by Hoxtygen** [comment]
> @Hoxtygen What version of the library are you using?

3.0.5

**Comment by tomix26** [comment]
@Hoxtygen That's weird because the most recent version is [2.3.0](https://github.com/zonkyio/embedded-database-spring-test/releases/tag/v2.3.0) 🙂

**Comment by Hoxtygen** [comment]
> @Hoxtygen That's weird because the most recent version is [2.3.0](https://github.com/zonkyio/embedded-database-spring-test/releases/tag/v2.3.0) 🙂

I might have misunderstood your question. I took it for what version of spring boot am I using? I'm not using embedded database.
