### ISSUE TITLE
Initializing the data source fails with the latest Flyway versions (7.5.1 and 7.5.2)

### ISSUE THREAD

**Issue by Dobiasd** [zonkyio/embedded-database-spring-test#149]
With Flyway version `7.5.0`, it still works fine. Version `7.5.1` and `7.5.2` however, produce the following error:

```
[...]
java.lang.IllegalStateException: Unexpected error occurred while initializing the data source
    at com.google.common.base.Preconditions.checkState(Preconditions.java:459)
    at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.getTarget(DefaultFlywayDataSourceContext.java:89)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195)
    at com.sun.proxy.$Proxy65.getConnection(Unknown Source)
    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:59)
    at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
    at org.flywaydb.core.Flyway.execute(Flyway.java:507)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
    at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
[...]
```

Below is the code of my minimal example to reproduce the problem:

## `Dockerfile`

```Dockerfile
FROM openjdk:11.0.10-jdk AS base

# Needed for embedded PostgreSQL-server to start during integration tests.
# see: https://github.com/zonkyio/embedded-database-spring-test
RUN groupadd --system --gid 1000 test
RUN useradd --system --gid test --uid 1000 --shell /bin/bash --create-home test
USER test
WORKDIR /home/test

ADD . /home/test/
RUN ./gradlew test

```

## `build.gradle`

```Groovy
buildscript {
    ext {
        kotlinVersion = '1.4.21'
        springBootVersion = '2.4.2'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-noarg:${kotlinVersion}")
    }
}

apply plugin: 'kotlin'
apply plugin: 'kotlin-spring'
apply plugin: 'kotlin-jpa'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.acme'
version = '1.0.0-SNAPSHOT'
sourceCompatibility = 1.8

compileKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: "${springBootVersion}"
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.18'
    implementation group: 'org.flywaydb', name: 'flyway-core', version: '7.5.2'

    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: "${kotlinVersion}"

    testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: "${springBootVersion}"
    testImplementation group: 'junit', name: 'junit', version: '4.13.1'

    testImplementation group: 'io.zonky.test', name: 'embedded-database-spring-test', version: '1.6.2'
}

test {
    testLogging {
        exceptionFormat = 'full'
    }
}

compileKotlin.dependsOn(processResources)
compileJava.dependsOn(processResources)

```

## `settings.gradle`

```Groovy
rootProject.name = 'flywayzonkytest'

```

## `src/main/kotlin/com/acme/flywayzonkytest/Application.kt`

```Kotlin
package com.acme.flywayzonkytest

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication


@SpringBootApplication
class Application


fun main(args: Array<String>) {
    runApplication<Application>(*args)
}

```

## `src/main/resources/application.yml`

```YAML
spring:
  flyway:
    enabled: true

```

## `src/main/resources/db/migration/V1__thing.sql`

```SQL
CREATE TABLE thing (
    some_id BIGINT PRIMARY KEY NOT NULL,
    some_name VARCHAR NOT NULL
);

```

## `src/test/kotlin/com/acme/flywayzonkytest/integration/CreateContextTest.kt`

```Kotlin
package com.acme.flywayzonkytest.integration

import io.zonky.test.db.AutoConfigureEmbeddedDatabase
import org.junit.Test
import org.junit.runner.RunWith
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.junit4.SpringRunner


@RunWith(SpringRunner::class)
@AutoConfigureEmbeddedDatabase
@SpringBootTest
class CreateContextTest {

    @Test
    fun `test create context`() {
    }

}

```

**Comment by tomix26** [comment]
Thanks for the report, I will fix it as soon as possible.

**Comment by Dobiasd** [comment]
Perfect, thanks a lot! :rocket:

Since the fixing commit is already merged into `master`, do you roughly know when version `1.6.3` will be released and available on Maven?

**Comment by tomix26** [comment]
I'll try to release it today.

**Comment by Dobiasd** [comment]
Cool, thanks again, also for this great library in general. It makes my integration tests so much simpler. Using H2 with `MODE=PostgreSQL` does not do the trick for me, because it does not support all Postgres-specific things I'm doing. Spinning up a separate Postgres instance in Docker adds quite some complexity. So `embedded-database-spring-test` is perfect for me. :slightly_smiling_face:

**Comment by tomix26** [comment]
Thank you. Glad to hear it! :smiling_face_with_three_hearts:

The new version has been released 🚀
