### ISSUE TITLE
BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource' defined in null

### ISSUE THREAD

**Issue by YashchenkoN** [zonkyio/embedded-database-spring-test#15]
```
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource' defined in null: Cannot register bean definition [Root bean: class [io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'dataSource': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari; factoryMethodName=dataSource; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:877)
	at io.zonky.test.db.postgres.EmbeddedPostgresContextCustomizerFactory$PreloadableEmbeddedPostgresRegistrar.postProcessBeanDefinitionRegistry(EmbeddedPostgresContextCustomizerFactory.java:162)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:530)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:418)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:139)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
```

Java version - 11
Spring Boot - v2.1.0.M2
Spring - v5.1.0.RC2

**Comment by tomix26** [comment]
Thanks for reporting it. The problem is caused by the following change https://github.com/spring-projects/spring-boot/issues/13609 that disables bean overriding by default in Spring Boot 2.1.0.

**Comment by tomix26** [comment]
@YashchenkoN Which version of the embedded database library are you using?

**Comment by YashchenkoN** [comment]
@tomix26 1.3.0

**Comment by YashchenkoN** [comment]
@tomix26 tried with 1.3.1. Still have the same issue

```
org.flywaydb.core.Flyway.getLocations()[Ljava/lang/String;
java.lang.NoSuchMethodError: org.flywaydb.core.Flyway.getLocations()[Ljava/lang/String;
```

**Comment by tomix26** [comment]
Ok, this is a bug on my side. I've created https://github.com/zonkyio/embedded-database-spring-test/issues/16 to fix that.

However, even if there was not this bug it wouldn't work. Because Spring Boot 2.1.0 requires Flyway 5.1.x but there is not a corresponding version of [flyway-test-extension](https://mvnrepository.com/artifact/org.flywaydb.flyway-test-extensions/flyway-spring-test) yet. The most recent version is flyway-spring-test:5.0.0 that is not compatible with Flyway 5.1.x. Which means it is not possible to use `@FlywayTest` annotation.

Because of Spring Boot 2.1.0 requires Flyway 5.1.x and it is not possible to downgrade to some previous version, and Flyway 5.1.x is missing the test extension, the only thing I can recommend you is to stay on Spring Boot 2.0.x.

**Comment by tomix26** [comment]
I've fixed the #16 issue, but as I said, it still does not work due to incompatibility with flyway-spring-test:5.0.0 test extension.

**Comment by YashchenkoN** [comment]
@tomix26 thank you for your response. I have created an issue for flyway-spring-test

**Comment by prabhushrikant** [comment]
> spring.main.allow-bean-definition-overriding=true

fixed my controller tests.

**Comment by sonu1304** [comment]
Thanks

**Comment by afreenpatel** [comment]
Thanks! solved my problem by adding property 
spring.main.allow-bean-definition-overriding=true

**Comment by aliluvtcode** [comment]
in which file do I need to add the spring.main.allow-bean-definition-overriding=true

**Comment by naveen2291** [comment]
Bean overriding can introduce major configuration issues and should not be enabled on non-test environments.

**Comment by raveenasharma456** [comment]
> Thanks! solved my problem by adding property
> spring.main.allow-bean-definition-overriding=true

Same question , pls answer

**Comment by JaloliddinXabibjonov** [comment]
> 

Thank you very much
