### ISSUE TITLE
2.0.0-beta1 - Docker failed to pull image

### ISSUE THREAD

**Issue by oeddyo** [zonkyio/embedded-database-spring-test#152]
Running on github action and found this:

```

                        Caused by:
                        org.testcontainers.containers.ContainerLaunchException: Container startup failed
                            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
                            at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:308)
                            at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$DatabaseInstance.<init>(DockerPostgresDatabaseProvider.java:173)
                            at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$DatabaseInstance.<init>(DockerPostgresDatabaseProvider.java:137)
                            at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$1.load(DockerPostgresDatabaseProvider.java:77)
                            at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$1.load(DockerPostgresDatabaseProvider.java:75)
                            at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
                            at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
                            at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
                            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
                            at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
                            at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
                            at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
                            at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider.createDatabase(DockerPostgresDatabaseProvider.java:113)
                            ... 14 more

                            Caused by:
                            org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:11-alpine, imagePullPolicy=DefaultPullPolicy())
                                at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1278)
                                at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:612)
                                at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:317)
                                ... 27 more

                                Caused by:
                                com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
                                    at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:125)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
                                    at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
                                    at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:91)
                                    at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:203)
                                    at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
                                    at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
                                    at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
                                    at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
                                    at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
                                    at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:66)
                                    at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27)
                                    at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
                                    at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
                                    at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1276)
                                    ... 29 more



```

**Comment by oeddyo** [comment]
maybe related: https://github.com/testcontainers/testcontainers-java/issues/3574
https://github.com/testcontainers/testcontainers-java/issues/3572

**Comment by oeddyo** [comment]
1.15.1 seems to fix it?

**Comment by oeddyo** [comment]
Sorry I wasn't being clear. But I'm using 2.0.0-beta1 so the issue was meant to report to the newer version but somehow it's combined on github

**Comment by oeddyo** [comment]
@tomix26 is it possible to update 2.0.0-beta1 too?

**Comment by tomix26** [comment]
Oh, I'm sorry. Not yet. But I plan to release a new beta next week. For now, you need to change the version of TestContainers manually. The version `1.15.1` fixes this issue.

**Comment by oeddyo** [comment]
No rush. Look forward to the fix

Thanks for this amazing software btw

**Comment by tomix26** [comment]
Version 2.0.0 has been finally released.
