### ISSUE TITLE
AWS CodeBuild docker container issues

### ISSUE THREAD

**Issue by karthikrao5** [zonkyio/embedded-database-spring-test#169]
I'm using the docker provider and want to use a clone of the postgres:12-alpine image that I have pushed to a private AWS ECR repository.

However, when I run my spring boot integration tests in AWS CodeBuild, I get the error that I have reached my pull limit from dockerhub.

```
Caused by:
--
85 | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is io.zonky.test.db.shaded.com.google.common.util.concurrent.UncheckedExecutionException: io.zonky.test.db.provider.ProviderException: Unexpected error when preparing a database cluster; nested exception is com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
86 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
87 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
88 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
89 | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
90 | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
91 | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
92 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
93 | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
94 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
95 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
96 | at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)
97 | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
98 | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
99 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
100 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
101 | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
102 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
103 | at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:123)
104 | at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
105 | at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)

```

In my application-test.yml configuration file I have the following: 
```
zonky:
  test:
    database:
      provider: docker
      type: postgres
      postgres:
        docker:
          image: account-id.dkr.ecr.region.amazonaws.com/postgres:12-alpine
```

As a test, I botched the spelling of the container name to something like (I've obfuscated my account ID when pasting the stack trace here. not like this when actually running):

```
          image: account-id.dkr.ecr.region.amazonaws.com/postgres:12-alpinesdf
```

And the stack trace for the error in CodeBuild is now:
```
Caused by:
--
131 | org.testcontainers.containers.ContainerLaunchException: Container startup failed
132 | at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
133 | at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
134 | at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$DatabaseInstance.<init>(DockerPostgresDatabaseProvider.java:173)
135 | at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$DatabaseInstance.<init>(DockerPostgresDatabaseProvider.java:137)
136 | at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$1.load(DockerPostgresDatabaseProvider.java:77)
137 | at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider$1.load(DockerPostgresDatabaseProvider.java:75)
138 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
139 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
140 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
141 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
142 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache.get(LocalCache.java:4147)
143 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
144 | at io.zonky.test.db.shaded.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
145 | at io.zonky.test.db.provider.postgres.DockerPostgresDatabaseProvider.createDatabase(DockerPostgresDatabaseProvider.java:113)
146 | ... 14 more
147 |  
148 | Caused by:
149 | org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=account-id.dkr.ecr.region.amazonaws.com/postgres:12-alpinesdf, imagePullPolicy=DefaultPullPolicy())
150 | at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1286)
151 | at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:615)
152 | at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
153 | ... 27 more
154 |  
155 | Caused by:
156 | com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"manifest for account-id.dkr.ecr.region.amazonaws.com/postgres:12-alpinesdf not found: manifest unknown: Requested image not found"}
157 | at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
158 | at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)

```

The stack trace with the misspelled container URI indicates zonky is correctly trying to pull a private repo NOT from the default docker registry. However, when spelled right, it seems like it is attempting to pull from Dockerhub. What other config do i need to specify to tell zonky to use a container from my private AWS ECR repo?

The build file does contain an AWS ECR login and it indicates that the build is successfully authenticated with ECR.

Thanks for the help!

**Comment by karthikrao5** [comment]
Update:

I think this is an AWS Permissions issue. You have to add the ecr:BatchGetImage policy to the service role. If the CodeBuild environment doesn't have access to pull from the private ECR repo, it defaults to dockerhub. Not sure if this is documented anywhere. Maybe we can add a section in the docs for private container registry?

**Comment by tomix26** [comment]
Ok, thanks for the info. I won't mention it in the documentation, as I think it's more related to AWS than to the library itself.

**Comment by karthikrao5** [comment]
@tomix26 I'm actually seeing the issue again in CI. The CI script is pulling the postgres:12-alpine container from my private ECR repo in a separate step, but when i run ```./gradlew test``` I still get the pull limit error from docker, even though i have 

```
zonky:
  test:
    database:
      provider: docker
      type: postgres
      postgres:
        docker:
          image: account-id.dkr.ecr.region.amazonaws.com/postgres:12-alpine
```

Sometimes it runs fine, sometimes i see the pull limit error. This leads me to believe it's not using the private repo at all and the successful runs are actually pulling dockerhub postgres container

**Comment by karthikrao5** [comment]
Seems like the issue is that the testcontainers dependency actually [pulls more](https://www.testcontainers.org/features/configuration/) than the database image. You either disable the additional checks (through env vars like 

```
TESTCONTAINERS_RYUK_DISABLED: true
TESTCONTAINERS_CHECKS_DISABLE: true
```

Or you also have to download the additional containers into your private registry.

**Comment by karthikrao5** [comment]
Also last piece`TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: account-id.dkr.ecr.region.amazonaws.com/` has to be specified for private registry containers.
