### ISSUE TITLE
Error creating bean with name 'flyway' when starting SpringBoot 2.5.2 after upgrade from 1.6.3 to 2.0.x

### ISSUE THREAD

**Issue by mnowrot** [zonkyio/embedded-database-spring-test#170]
Please see the error message below:

```text

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

???????
|  flyway defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]
?     ?
|  dataSource
?     ?
|  dataSourceContext
?     ?
|  springConfig defined in file [edited]
?     ?
|  edited defined in class path resource [edited]
?     ?
|  edited defined in edited defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration
?     ?
|  (inner bean)#fe30f54
???????

```

Exception:

```text
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'flyway': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:227)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 155 common frames omitted
```

This started happening after upgrading embedded-database-spring-test from 1.6.3 to 2.0.0. or 2.0.1

I'll be happy to deliver more details upon request

**Comment by tomix26** [comment]
To investigate the problem I need a complete log, without edited bean names. If you don't want to post the log publicly, you can send it to my private email address: tomix26@gmail.com. I further need to know if you are using any custom implementation of [database provider](https://github.com/zonkyio/embedded-database-spring-test/blob/master/embedded-database-spring-test/src/main/java/io/zonky/test/db/provider/DatabaseProvider.java) or some other internal classes?

**Comment by mnowrot** [comment]
I've sent an email with the logs. We do not use any custom implementations of the database provider or any other internal classes.

**Comment by tomix26** [comment]
Thanks for the logs, it helped a lot. It seems there is some implicit dependency between `dataSourceContext` and `springConfig` beans. I suspect that this dependency could be caused by the definition of a `TaskExecutor` bean in `SpringConfig` configuration. So is there any such executor bean present? If so, could you please try to move it to a separate configuration class?

**Comment by mnowrot** [comment]
Thank you @tomix26 for your support, the proposed workaround was spot-on and we were able to upgrade to 2.0.1
