### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by YashchenkoN** [zonkyio/embedded-database-spring-test#19]
```
org/flywaydb/core/internal/util/scanner/Scanner
java.lang.NoClassDefFoundError: org/flywaydb/core/internal/util/scanner/Scanner
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.createMigrationResolver(OptimizedFlywayTestExecutionListener.java:240)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.findFirstVersion(OptimizedFlywayTestExecutionListener.java:210)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.isAppendable(OptimizedFlywayTestExecutionListener.java:200)
````

Spring version - 5.1.1.RELEASE
Spring Boot version - 2.1.0.RC1
Flyway version - 5.2.0
Flyway test extension - 5.1.0
Embedded database spring test version - 1.3.2

**Comment by YashchenkoN** [comment]
Looks like Scanner is moved to the new package org.flywaydb.core.internal.scanner

**Comment by YashchenkoN** [comment]
Please take a look on PR #20

**Comment by tomix26** [comment]
Great work! Thanks a lot.
