### ISSUE TITLE
Problem with embedded postgres

### ISSUE THREAD

**Issue by IlyaMesh** [zonkyio/embedded-database-spring-test#194]
Hi, got problem in my work project, and it might be connected with zonky.
So we're using this verson 
>dependency 'io.zonky.test:embedded-postgres:1.3.1'

And then, while gradle do the task with embedded postgres I got the following:

> [main] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - Detected a Darwin x86_64 system
[main] INFO io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver - Detected distribution: 'Unknown'
[main] INFO io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver - System specific postgres binaries found: 'postgres-darwin-x86_64.txz'
[main] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - Postgres binaries at /var/folders/wj/whf15pks0f3_4hvnrt2r8wzm0000gp/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3
[initdb:pid(9418)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - no data was returned by command ""/private/var/folders/wj/whf15pks0f3_4hvnrt2r8wzm0000gp/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/postgres" -V"
[initdb:pid(9418)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - The program "postgres" is needed by initdb but was not found in the
[initdb:pid(9418)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - same directory as "/private/var/folders/wj/whf15pks0f3_4hvnrt2r8wzm0000gp/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/initdb".
[initdb:pid(9418)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - Check your installation.
[main] ERROR ru.vtb.investmentprofilecps.commons.jooq.PostgresLiquibaseDatabase - create0() error
java.lang.IllegalStateException: Process [/var/folders/wj/whf15pks0f3_4hvnrt2r8wzm0000gp/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/wj/whf15pks0f3_4hvnrt2r8wzm0000gp/T/epg13923045853098707358, -E, UTF-8] failed
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.system(EmbeddedPostgres.java:632)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.initdb(EmbeddedPostgres.java:252)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:159)
	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:583)
	at ru.vtb.investmentprofilecps.commons.jooq.PostgresLiquibaseDatabase.create0(PostgresLiquibaseDatabase.java:37)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:342)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:332)
	at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:322)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:546)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:239)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:234)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:206)
	

P.s. I found info that it could be related with os version, so I'm using macOS 12.2.1

**Comment by IlyaMesh** [comment]
Upd.
Solved with comment under another issue
