### ISSUE TITLE
FlywayEmbeddedPostgresDataSourceFactoryBean Failing to initialize

### ISSUE THREAD

**Issue by maxkramerbcgdv** [zonkyio/embedded-database-spring-test#4]
Hey, thanks for your great work!

I've just finished implementing this in a current project, and everything is working perfectly locally.

Having deployed this to a gradle:alpine Docker image, we're receiving the following error when running our tests:

```
ERROR i.z.t.d.p.FlywayEmbeddedPostgresDataSourceFactoryBean - Unexpected error during the initialization of embedded database
    java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Cannot run program "/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb": error=2, No such file or directory
```

Having attempted to debug, I listed the output of the `/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin` directory, and it does contain the initdb script. I also verified the permissions of this folder and script, and they are the same permissions and user as the one that is running our tests.

```
ls -laR /tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin
/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin:
total 6388
drwxr-xr-x    2 gradle   gradle        4096 Mar 11 16:26 .
drwxr-xr-x    5 gradle   gradle        4096 Mar 11 16:26 ..
-rwxr--r--    1 gradle   gradle       94704 Mar 11 16:26 initdb
-rwxr--r--    1 gradle   gradle       37928 Mar 11 16:26 pg_ctl
-rwxr--r--    1 gradle   gradle     6391624 Mar 11 16:26 postgres
~/project $
```

Larger stack trace:

```
 Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb": error=2, No such file or directory
    	at com.google.common.base.Throwables.propagate(Throwables.java:241)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres.system(EmbeddedPostgres.java:514)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres.initdb(EmbeddedPostgres.java:208)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:130)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:493)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres.start(EmbeddedPostgres.java:413)
    	at com.opentable.db.postgres.embedded.PreparedDbProvider.createOrFindPreparer(PreparedDbProvider.java:76)
    	at com.opentable.db.postgres.embedded.PreparedDbProvider.<init>(PreparedDbProvider.java:59)
    	at com.opentable.db.postgres.embedded.PreparedDbProvider.forPreparer(PreparedDbProvider.java:53)
    	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.lambda$reload$0(DefaultFlywayDataSourceContext.java:111)
    	... 79 common frames omitted
    Caused by: java.io.IOException: Cannot run program "/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb": error=2, No such file or directory
    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    	at com.opentable.db.postgres.embedded.EmbeddedPostgres.system(EmbeddedPostgres.java:508)
    	... 87 common frames omitted
    Caused by: java.io.IOException: error=2, No such file or directory
    	at java.lang.UNIXProcess.forkAndExec(Native Method)
    	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    	... 88 common frames omitted
```

**Comment by tomix26** [comment]
Hi, thanks for reporting the issue.

It seems that the problem is caused by an incompatibility of postgres binaries included in [otj-pg-embedded](https://github.com/opentable/otj-pg-embedded) component, which our library depends on, with Alpine linux. This is because Alpine linux uses [musl libc](http://www.musl-libc.org/) instead of [glibc](http://www.etalabs.net/compare_libcs.html) and that probably causes your problem.

So, I can only recommed you to use non-alpine version of the gradle docker image. I tested the version `4.6.0-jdk8` and it works fine.

Is this answer sufficient for you?

Tomas

**Comment by maxkramerbcgdv** [comment]
Hey @tomix26, thanks for the response. you're right, I tested this earlier and it does work with the non-alpine image. Might be worth saying in the README just for future reference ;) 

Thanks for your help!

**Comment by tomix26** [comment]
You're right, I'll mention it in the documentation. Thanks for the feedback.
