### ISSUE TITLE
Fix compatibility with Flyway 6.0.3+

### ISSUE THREAD

**Issue by tomix26** [zonkyio/embedded-database-spring-test#67]
Since version 6.0.3, there is some incompatibility that will need to be resolved.
```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.createMigrationResolver(OptimizedFlywayTestExecutionListener.java:268)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.resolveMigrations(OptimizedFlywayTestExecutionListener.java:239)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.findFirstVersion(OptimizedFlywayTestExecutionListener.java:221)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.isAppendable(OptimizedFlywayTestExecutionListener.java:211)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.reloadDataSource(OptimizedFlywayTestExecutionListener.java:182)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.optimizedDbReset(OptimizedFlywayTestExecutionListener.java:148)
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.beforeTestMethod(OptimizedFlywayTestExecutionListener.java:114)
```

**Comment by tomix26** [comment]
Compatibility was broken by the following change https://github.com/flyway/flyway/issues/2482
