### ISSUE TITLE
Support postgis extensions

### ISSUE THREAD

**Issue by MarkVink** [zonkyio/embedded-database-spring-test#85]
I'm working on migration my application from MySQL to Postgres. One step that I need to solve is spinning up a Postgres database for running my unit tests. However, I use PostGIS to use geometry in my application. Is there a way to support Postgres extensions in this library?

When I try to create the extension using liquibase the test fails since the extensions seem not included.

> Caused by: org.postgresql.util.PSQLException: ERROR: could not open extension control file "/private/var/folders/8r/j5xh8qjx63b0j6wgm66w39q80000gn/T/embedded-pg/PG-2c0c4f55a015ab253337e3d05ca5fd21/share/postgresql/extension/postgis.control": No such file or directory
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272) ~[postgresql-42.2.10.jar:42.2.10]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267) ~[postgresql-42.2.10.jar:42.2.10]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398) ~[liquibase-core-3.8.7.jar:na]
	... 54 common frames omitted

**Comment by tomix26** [comment]
Yes, it is. You can use the [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) together with https://hub.docker.com/r/mdillon/postgis image or any other docker image that is compatible with the [official Postgres image](https://hub.docker.com/_/postgres).

**Comment by MarkVink** [comment]
Thank you for your suggestion. It will take me some time to look into using a Docker image and integrate it into my pipeline. Therefore you can close my questions.
