### ISSUE TITLE
Flyway 6.0.8 Compatibility

### ISSUE THREAD

**Issue by pabloedm** [zonkyio/embedded-database-spring-test#90]
Hello, 

I'm experiencing troubles with Flyway 6.0.8. 
`
java.lang.NoSuchMethodError: 'java.lang.String[] org.flywaydb.core.Flyway.getLocations()'
	at org.flywaydb.test.FlywayTestExecutionListener.locationsMigrationHandling(FlywayTestExecutionListener.java:444) ~[flyway-spring-test-5.0.0.jar:5.0.0]
	at org.flywaydb.test.FlywayTestExecutionListener.dbResetWithAnnotation(FlywayTestExecutionListener.java:399) ~[flyway-spring-test-5.0.0.jar:5.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283) ~[spring-core-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at io.zonky.test.db.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:44) ~[embedded-database-spring-test-1.5.3.jar:na]
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.originalDbReset(OptimizedFlywayTestExecutionListener.java:169) ~[embedded-database-spring-test-1.5.3.jar:na]
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.optimizedDbReset(OptimizedFlywayTestExecutionListener.java:152) ~[embedded-database-spring-test-1.5.3.jar:na]
	at io.zonky.test.db.flyway.OptimizedFlywayTestExecutionListener.beforeTestClass(OptimizedFlywayTestExecutionListener.java:101) ~[embedded-database-spring-test-1.5.3.jar:na]
	at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:213) ~[spring-test-5.2.4.RELEASE.jar:5.2.4.RELEASE]`

Is it compatible? If yes could you tell me how can I bypass this error?
Thanks.

**Comment by tomix26** [comment]
Hi, it seems that you need to upgrade `org.flywaydb.flyway-test-extensions:flyway-spring-test` dependency to a newer version. This https://mvnrepository.com/artifact/org.flywaydb.flyway-test-extensions/flyway-spring-test/6.0.0 should fit to your version of Flyway.

**Comment by pabloedm** [comment]
Yeah, you are right.
Thanks for your fast response.
