### ISSUE TITLE
IllegalStateException in Gitlab

### ISSUE THREAD

**Issue by fletchgqc** [zonkyio/embedded-database-spring-test#91]
My test is working perfectly on my local machine (Mac). However, on Gitlab the test consistently fails with this error:

```
2020-05-05 08:33:46.060 ERROR 233 --- [    Test worker] wayEmbeddedPostgresDataSourceFactoryBean : Unexpected error during the initialization of embedded database
     java.util.concurrent.CompletionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Process [/tmp/embedded-pg/PG-a8263178df5b3591feca6b619939c2bb/bin/initdb, -A, trust, -U, postgres, -D, /tmp/epg7983335201399578710, -E, UTF-8] failed
     	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.lambda$reload$0(DefaultFlywayDataSourceContext.java:113)
     	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
     	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
     	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:677)
     	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
     	at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:2104)
     	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.reload(DefaultFlywayDataSourceContext.java:106)
     	at io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean.postProcessBeforeInitialization(FlywayEmbeddedPostgresDataSourceFactoryBean.java:89)

```
The only setup I've done is to simply add @AutoConfigureEmbeddedDatabase to my test.

I saw a couple of other issues here which might be related, but I'm not sure as the message is different.

**Comment by tomix26** [comment]
I suppose the problem is that the tests on Gitlab run with root user. Try this https://github.com/zonkyio/embedded-database-spring-test/issues/77#issuecomment-577076464 and let me know if it helps you.

**Comment by fletchgqc** [comment]
This worked, thanks. I suggest to close this issue, and we can continue the discussion there.
