### ISSUE TITLE
Test failure with following error.

### ISSUE THREAD

**Issue by arunavynair** [zonkyio/embedded-database-spring-test#92]
I start using this in my Sprint boot app and all test pass locally, but having an issue part of Jenkins build. How can i fix it ?
Tests are running in a docker image

```    [30m2020-05-06 08:01:26,436[0;39m [1;31mERROR[0;39m [[34mTest worker[0;39m] [33mio.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean[0;39m: Unexpected error during the initialization of embedded database
    java.util.concurrent.CompletionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Process [/tmp/embedded-pg/PG-a8263178df5b3591feca6b619939c2bb/bin/initdb, -A, trust, -U, postgres, -D, /tmp/epg3673142760824335673, -E, UTF-8, --lc-monetary=en_GB.UTF-8, --lc-numeric=en_GB.UTF-8, --lc-collate=en_GB.UTF-8, --username=postgres] failed
    	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.lambda$reload$0(DefaultFlywayDataSourceContext.java:113)
    	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
    	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
    	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:613)
    	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:631)
    	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:2006)
    	at io.zonky.test.db.flyway.DefaultFlywayDataSourceContext.reload(DefaultFlywayDataSourceContext.java:106)
    	at io.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean.postProcessBeforeInitialization(FlywayEmbeddedPostgresDataSourceFactoryBean.java:89)
```

```
    Caused by: java.lang.IllegalStateException: Process [/tmp/embedded-pg/PG-a8263178df5b3591feca6b619939c2bb/bin/initdb, -A, trust, -U, postgres, -D, /tmp/epg4542884291989082376, -E, UTF-8, --lc-monetary=en_GB.UTF-8, --lc-numeric=en_GB.UTF-8, --lc-collate=en_GB.UTF-8, --username=postgres] failed
    	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.system(EmbeddedPostgres.java:631)
    	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.initdb(EmbeddedPostgres.java:249)
    	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:156)
    	at io.zonky.test.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:584)
    	at io.zonky.test.db.provider.impl.ZonkyPostgresDatabaseProvider$DatabaseInstance.<init>(ZonkyPostgresDatabaseProvider.java:128)
    	at io.zonky.test.db.provider.impl.ZonkyPostgresDatabaseProvider$DatabaseInstance.<init>(ZonkyPostgresDatabaseProvider.java:112)
    	at io.zonky.test.db.provider.impl.ZonkyPostgresDatabaseProvider$1.load(ZonkyPostgresDatabaseProvider.java:59)
    	at io.zonky.test.db.provider.impl.ZonkyPostgresDatabaseProvider$1.load(ZonkyPostgresDatabaseProvider.java:57)
    	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
    	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
    	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
    	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
    	... 11 common frames omitted

    2020-05-06 08:11:18.447  INFO [,,,] 79 --- [initdb:pid(135)] i.z.t.d.p.embedded.EmbeddedPostgres      : initdb: cannot be run as root
    [30m2020-05-06 08:11:18,447[0;39m [34mINFO [0;39m [[34minitdb:pid(135)[0;39m] [33mjava.util.Iterator[0;39m: initdb: cannot be run as root
    2020-05-06 08:11:18.450  INFO [,,,] 79 --- [initdb:pid(135)] i.z.t.d.p.embedded.EmbeddedPostgres      : Please log in (using, e.g., "su") as the (unprivileged) user that will
    [30m2020-05-06 08:11:18,450[0;39m [34mINFO [0;39m [[34minitdb:pid(135)[0;39m] [33mjava.util.Iterator[0;39m: Please log in (using, e.g., "su") as the (unprivileged) user that will
    2020-05-06 08:11:18.450  INFO [,,,] 79 --- [initdb:pid(135)] i.z.t.d.p.embedded.EmbeddedPostgres      : own the server process.
    [30m2020-05-06 08:11:18,450[0;39m [34mINFO [0;39m [[34minitdb:pid(135)[0;39m] [33mjava.util.Iterator[0;39m: own the server process.
    [30m2020-05-06 08:11:18,446[0;39m [1;31mERROR[0;39m [[34mTest worker[0;39m] [33mio.zonky.test.db.postgres.FlywayEmbeddedPostgresDataSourceFactoryBean[0;39m: Unexpected error during the initialization of embedded database
```

**Comment by tomix26** [comment]
PostgreSQL database cannot be run as root.
> `2020-05-06 08:11:18.447  INFO [,,,] 79 --- [initdb:pid(135)] i.z.t.d.p.embedded.EmbeddedPostgres      : initdb: cannot be run as root`

More information about this issue is here: https://github.com/zonkyio/embedded-database-spring-test/issues/77
